In [6]:
# Importación de librerias
import pandas as pd
from pathlib import Path

In [7]:
# IMPORTACION DE DATOS DEL 2025

ANIO = '2025' # Año bajo estudio
ARCHIVO = 'epi_2025.xlsx' # Dataset
DIRECTORIO = Path.cwd().parent / "data" / "raw" / ARCHIVO

# Para CSV
# df = pd.read_csv(file_path)

# Para Excel (XLSX)
df = pd.read_excel(DIRECTORIO)

df

,SEMEPI,FECHA,MES,EDAD,SEXO,LOCALIDAD,CONSULTA,MÉDICO,DIAGNOSTIC,ACCIDENTE
0,1,12/29,DICIEMBRE,5,NaN,PARANA,GUARDIA,RESIDENTES,ACCIDENTES,HERIDAS
1,1,12/29,DICIEMBRE,7,NaN,PARANA,GUARDIA,RESIDENTES,ALGIAS,NINGUNO
2,1,12/29,DICIEMBRE,6,NaN,PARANA,GUARDIA,RESIDENTES,ACCIDENTES,TRAUMATISMO
3,1,12/29,DICIEMBRE,6,NaN,PARANA,GUARDIA,RESIDENTES,GEA,NINGUNO
4,1,12/29,DICIEMBRE,9,NaN,PARANA,GUARDIA,RESIDENTES,FIEBRE,NINGUNO
...,...,...,...,...,...,...,...,...,...,...
51887,53,01/03,ENERO,11,NaN,PARANA,GUARDIA,RESIDENTES,OTITIS,NINGUNO
51888,53,01/03,ENERO,4,NaN,PARANA,GUARDIA,RESIDENTES,GEA,NINGUNO
51889,53,01/03,ENERO,5,NaN,PARANA,GUARDIA,RESIDENTES,DERMATOLOGICAS,NINGUNO
51890,53,01/03,ENERO,3,NaN,PARANA,GUARDIA,RESIDENTES,CONTROL,NINGUNO
51891,53,01/03,ENERO,5,NaN,PARANA,GUARDIA,RESIDENTES,CONTROL,NINGUNO

In [9]:
# Prueba de las funciones creadas con este código
# Importación de librerias
import pandas as pd
from pathlib import Path
import sys

sys.path.append(str(Path.cwd().parent / "src"))

from importacion.leer_epiinfo import leer_excel

leer_excel(2025)

,SEMEPI,FECHA,MES,EDAD,SEXO,LOCALIDAD,CONSULTA,MÉDICO,DIAGNOSTIC,ACCIDENTE
0,1,12/29,DICIEMBRE,5,NaN,PARANA,GUARDIA,RESIDENTES,ACCIDENTES,HERIDAS
1,1,12/29,DICIEMBRE,7,NaN,PARANA,GUARDIA,RESIDENTES,ALGIAS,NINGUNO
2,1,12/29,DICIEMBRE,6,NaN,PARANA,GUARDIA,RESIDENTES,ACCIDENTES,TRAUMATISMO
3,1,12/29,DICIEMBRE,6,NaN,PARANA,GUARDIA,RESIDENTES,GEA,NINGUNO
4,1,12/29,DICIEMBRE,9,NaN,PARANA,GUARDIA,RESIDENTES,FIEBRE,NINGUNO
...,...,...,...,...,...,...,...,...,...,...
51887,53,01/03,ENERO,11,NaN,PARANA,GUARDIA,RESIDENTES,OTITIS,NINGUNO
51888,53,01/03,ENERO,4,NaN,PARANA,GUARDIA,RESIDENTES,GEA,NINGUNO
51889,53,01/03,ENERO,5,NaN,PARANA,GUARDIA,RESIDENTES,DERMATOLOGICAS,NINGUNO
51890,53,01/03,ENERO,3,NaN,PARANA,GUARDIA,RESIDENTES,CONTROL,NINGUNO
51891,53,01/03,ENERO,5,NaN,PARANA,GUARDIA,RESIDENTES,CONTROL,NINGUNO