In [1]:
import pandas as pd
from datetime import datetime
from pathlib import Path
import sys

sys.path.append(str(Path.cwd().parent / "src"))

from importacion.leer_epiinfo import leer_excel

df = leer_excel(2025)

df

,SEMEPI,FECHA,MES,EDAD,SEXO,LOCALIDAD,CONSULTA,MÉDICO,DIAGNOSTIC,ACCIDENTE
0,1,12/29,DICIEMBRE,5,NaN,PARANA,GUARDIA,RESIDENTES,ACCIDENTES,HERIDAS
1,1,12/29,DICIEMBRE,7,NaN,PARANA,GUARDIA,RESIDENTES,ALGIAS,NINGUNO
2,1,12/29,DICIEMBRE,6,NaN,PARANA,GUARDIA,RESIDENTES,ACCIDENTES,TRAUMATISMO
3,1,12/29,DICIEMBRE,6,NaN,PARANA,GUARDIA,RESIDENTES,GEA,NINGUNO
4,1,12/29,DICIEMBRE,9,NaN,PARANA,GUARDIA,RESIDENTES,FIEBRE,NINGUNO
...,...,...,...,...,...,...,...,...,...,...
51887,53,01/03,ENERO,11,NaN,PARANA,GUARDIA,RESIDENTES,OTITIS,NINGUNO
51888,53,01/03,ENERO,4,NaN,PARANA,GUARDIA,RESIDENTES,GEA,NINGUNO
51889,53,01/03,ENERO,5,NaN,PARANA,GUARDIA,RESIDENTES,DERMATOLOGICAS,NINGUNO
51890,53,01/03,ENERO,3,NaN,PARANA,GUARDIA,RESIDENTES,CONTROL,NINGUNO
51891,53,01/03,ENERO,5,NaN,PARANA,GUARDIA,RESIDENTES,CONTROL,NINGUNO

In [2]:
# Eliminación de las columnas SEXO, LOCALIDAD, CONSULTA Y MÉDICO
df.drop(columns=['SEXO', 'LOCALIDAD', 'CONSULTA', 'MÉDICO'], inplace=True)

df

       SEMEPI  FECHA        MES EDAD      DIAGNOSTIC    ACCIDENTE
0           1  12/29  DICIEMBRE    5      ACCIDENTES      HERIDAS
1           1  12/29  DICIEMBRE    7          ALGIAS      NINGUNO
2           1  12/29  DICIEMBRE    6      ACCIDENTES  TRAUMATISMO
3           1  12/29  DICIEMBRE    6             GEA      NINGUNO
4           1  12/29  DICIEMBRE    9          FIEBRE      NINGUNO
...       ...    ...        ...  ...             ...          ...
51887      53  01/03      ENERO   11          OTITIS      NINGUNO
51888      53  01/03      ENERO    4             GEA      NINGUNO
51889      53  01/03      ENERO    5  DERMATOLOGICAS      NINGUNO
51890      53  01/03      ENERO    3         CONTROL      NINGUNO
51891      53  01/03      ENERO    5         CONTROL      NINGUNO

[51892 rows x 6 columns]

In [3]:
# CAMBIO DEL FORMATO DE LA FECHA, SE LE AGREGA EL AÑO Y SE CAMBIA EL TIPO DE DATO

# Esto es para el dataset del 2025 en donde:
#  * Si SEMEPI = 1 y MES = DICIEMBRE => AÑO = 2024
#  * Si SEMEPI = 53 y MES = ENERO => AÑO = 2026
#  * Para el resto de los casos AÑO = 2025

for i in range(len(df['FECHA'])):

  dia = df['FECHA'][i].split('/')[1]
  mes = df['FECHA'][i].split('/')[0]
  fecha = ''

  if (mes == "12" and df['SEMEPI'][i] == 1): 
    fecha = (dia + '/' + mes + '/' + '2024')

  elif (mes == "01" and df['SEMEPI'][i] == 53): 
    fecha = (dia + '/' + mes + '/' + '2026')
  else: 
    fecha = (dia + '/' + mes + '/' + '2025')
  #print(type(dia), mes)
  #fecha = df['FECHA'][i].split('/')[1] + '/' + df['FECHA'][i].split('/')[0] + '/' + ANIO
  df.at[i,'FECHA'] = fecha

df['FECHA'] = pd.to_datetime(df['FECHA'], format='%d/%m/%Y')
df

       SEMEPI      FECHA        MES EDAD      DIAGNOSTIC    ACCIDENTE
0           1 2024-12-29  DICIEMBRE    5      ACCIDENTES      HERIDAS
1           1 2024-12-29  DICIEMBRE    7          ALGIAS      NINGUNO
2           1 2024-12-29  DICIEMBRE    6      ACCIDENTES  TRAUMATISMO
3           1 2024-12-29  DICIEMBRE    6             GEA      NINGUNO
4           1 2024-12-29  DICIEMBRE    9          FIEBRE      NINGUNO
...       ...        ...        ...  ...             ...          ...
51887      53 2026-01-03      ENERO   11          OTITIS      NINGUNO
51888      53 2026-01-03      ENERO    4             GEA      NINGUNO
51889      53 2026-01-03      ENERO    5  DERMATOLOGICAS      NINGUNO
51890      53 2026-01-03      ENERO    3         CONTROL      NINGUNO
51891      53 2026-01-03      ENERO    5         CONTROL      NINGUNO

[51892 rows x 6 columns]

In [4]:
# ELIMINACIÓN DE LA COLUMNA DEL MES POR CONSIDERARSE REDUNDANTE Y 
# AGREGAMOS UNA COLUMNA PARA IDENTIFICAR EL AÑO EPIDEMIOLÓGICO
# AGREGAMOS COLUMNA PARA IDENTIFICAR EL DÍA DE LA SEMANA

df.drop(columns=['MES'], inplace=True)

df.insert(loc=1, column= 'ANIOEPI', value=2025)

df.insert(loc=2, column= 'DIA', value=df['FECHA'].dt.day_name())

#df['DIA'] = df['FECHA'].dt.day_name()
df['DIA'] = df['DIA'].replace({'Sunday': 'DOMINGO',
                               'Monday': 'LUNES',
                               'Tuesday' : 'MARTES',
                               'Wednesday': 'MIERCOLES',
                               'Thursday' : 'JUEVES',
                               'Friday' : 'VIERNES',
                               'Saturday' : 'SABADO'})

df

       SEMEPI  ANIOEPI      DIA      FECHA EDAD      DIAGNOSTIC    ACCIDENTE
0           1     2025  DOMINGO 2024-12-29    5      ACCIDENTES      HERIDAS
1           1     2025  DOMINGO 2024-12-29    7          ALGIAS      NINGUNO
2           1     2025  DOMINGO 2024-12-29    6      ACCIDENTES  TRAUMATISMO
3           1     2025  DOMINGO 2024-12-29    6             GEA      NINGUNO
4           1     2025  DOMINGO 2024-12-29    9          FIEBRE      NINGUNO
...       ...      ...      ...        ...  ...             ...          ...
51887      53     2025   SABADO 2026-01-03   11          OTITIS      NINGUNO
51888      53     2025   SABADO 2026-01-03    4             GEA      NINGUNO
51889      53     2025   SABADO 2026-01-03    5  DERMATOLOGICAS      NINGUNO
51890      53     2025   SABADO 2026-01-03    3         CONTROL      NINGUNO
51891      53     2025   SABADO 2026-01-03    5         CONTROL      NINGUNO

[51892 rows x 7 columns]

In [7]:
# Prueba de las funciones creadas con este código
# Importación de librerias

sys.path.append(str(Path.cwd().parent / "src"))

from limpieza.limpieza import limpiar_2025

limpiar_2025()

ValueError: time data "12/29" doesn't match format "%d/%m/%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.